[project]
name = "tessera-test-suites"
version = "0.1.0"
description = "Vector + perf tests for Tessera"
authors = [{ name = "prasad-kumkar", email = "prasad@chainscore.finance" }]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = "^3.12"
package-mode = false

[tool.poetry.dependencies]
deepdiff = "^6.5.0"
python = "^3.12"
pytest = "^8.0"
pytest-benchmark = "^4.0.0"
pytest-profiling = "^1.7.0"
memory-profiler = "^0.61.0"
psutil = "^5.9.0"
matplotlib = "^3.7.0"
tessera = {path = "../tsr-py", develop = true}
rockstore = "0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
