[project]
name = "tessera-test-suites"
version = "0.1.0"
description = "Vector + perf tests for Tessera"
authors = [{ name = "prasad-kumkar", email = "prasad@chainscore.finance" }]
license = { text = "Apache-2.0" }
readme = "README.md"
package-mode = false
dependencies = [
    "tessera[test]",  # This pulls in all test dependencies from main project
    "rockstore>=0.1.2"
]

[tool.uv.sources]
tessera = { workspace = true }
rockstore = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
