#!/bin/bash

# Build All JAM Services

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLAYGROUND_DIR="$(dirname "$SCRIPT_DIR")"

echo "🔨 Building JAM Services..."

# Change to services directory
cd "$PLAYGROUND_DIR/services"

# Check if jam-pvm-build is available
if ! command -v jam-pvm-build &> /dev/null; then
    echo "❌ jam-pvm-build not found. Install JAM PVM build tools first."
    exit 1
fi

# Service to build
SERVICE=$1

# Create output directory
mkdir -p "$PLAYGROUND_DIR/builds"

# Track build results
SUCCESSFUL_BUILDS=()
FAILED_BUILDS=()

echo "📦 Building service: $SERVICE"
echo ""

echo "🏗️  Building $SERVICE service..."

if [ ! -d "$SERVICE" ]; then
    echo "⚠️  Service directory $SERVICE not found, skipping..."
    FAILED_BUILDS+=("$SERVICE (not found)")
    exit 1
fi

# Build the service
# Build PVM bytecode
if jam-pvm-build --profile release --module service --output "../builds/${SERVICE}-service.jam" "$SERVICE"; then
    BYTECODE_FILE="../builds/${SERVICE}-service.jam"
    if [ -f "$BYTECODE_FILE" ]; then
        echo "✅ PVM bytecode generated: $BYTECODE_FILE"
        SUCCESSFUL_BUILDS+=("$SERVICE")
    else
        echo "❌ PVM bytecode not found for $SERVICE"
        FAILED_BUILDS+=("$SERVICE (no bytecode)")
    fi
else
    echo "❌ PVM build failed for $SERVICE"
    FAILED_BUILDS+=("$SERVICE (pvm build)")
fi
echo ""

# Summary
echo "📊 Build Summary:"
echo "=================="

if [ ${#SUCCESSFUL_BUILDS[@]} -gt 0 ]; then
    echo "✅ Successful builds (${#SUCCESSFUL_BUILDS[@]}):"
    for service in "${SUCCESSFUL_BUILDS[@]}"; do
        echo "  - $service"

        BYTECODE_PATH="$PLAYGROUND_DIR/builds/${service}-service.jam"
        if [ -f "$BYTECODE_PATH" ]; then
            SIZE=$(ls -lh "$BYTECODE_PATH" | awk '{print $5}')
            echo "    Size: $SIZE"
        fi
    done
    echo ""
fi

if [ ${#FAILED_BUILDS[@]} -gt 0 ]; then
    echo "❌ Failed builds (${#FAILED_BUILDS[@]}):"
    for service in "${FAILED_BUILDS[@]}"; do
        echo "  - $service"
    done
    echo ""
fi

# List all generated bytecode files
echo "📁 Generated bytecode files:"
if ls "$PLAYGROUND_DIR/builds"/*.jam 1> /dev/null 2>&1; then
    ls -lh "$PLAYGROUND_DIR/builds"/*.jam | while read -r line; do
        echo "  $line"
    done
else
    echo "  (none)"
fi

echo ""
echo "🎯 Next steps:"
echo "  - Start network: ./scripts/start-devnet.sh"
echo "  - Deploy services: ./scripts/deploy-services.sh"
echo "  - Test services: ./scripts/test-services.sh"

# Exit with error if any builds failed
if [ ${#FAILED_BUILDS[@]} -gt 0 ]; then
    exit 1
fi

echo "🎉 All services built successfully!"
