[workspace]
members = [
    "hello",
    "counter",
    "peek",
    "zero",
    "poke",
    "gas",
    "gas_probe",
    "is_available",
    "is_available_accu",
    "expunge",
    "machine",
    "machineNexpunge",
    "machineNzeroNvoid",
    "void",
    "create_service",
    "get_storage",
    "set_storage",
    "update_storage",
    "create_storage",
    "create_service_storage",
    "checkpoint",
    "get",
    "set",
    "foreign_lookup",
    "foreign_lookup_into",
    "is_foreign_available",
    "lookup",
    "lookup2",
    "lookup_into",
    "peek_into",
    "ejectt"
]

resolver = "2"

[workspace.dependencies]
jam-types = { version = "0.1.22", default-features = false }
jam-pvm-common = { version = "0.1.22", features = [
    "service",
    "logging",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
types = { path = "../../types" }

[workspace.package]
authors = ["Chainscore Labs"]
license = "MIT"
